/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainWindow (void);
GtkWidget* create_itemDlg (void);
GtkWidget* create_aboutDlg (void);
GtkWidget* create_settingsDlg (void);
